version: '3.4'

services:
  primenumberapi:
    image: primenumberapi:dev
    build:
      target: base
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_primenumberapi$
    volumes:
      - C:\Users\Jespe\source\repos\PrimeNumberAPI\PrimeNumberAPI:/app
      - C:\Users\Jespe\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_primenumberapi$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_primenumberapi$ bin/Debug/netcoreapp2.2/PrimeNumberAPI.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""
